name: macOS Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-15-intel

    steps:
      - name: Check macOS
        run: |
          sw_vers
          uname -a

      - name: Check compiler
        run: |
          clang --version
